[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
numReplicas = 1

[variables]
NODE_ENV = "production"

# Add these as environment variables in Railway dashboard:
# DATABASE_URL (will be automatically added when you attach MySQL)
# FRONTEND_URL
# PAYSTACK_SECRET_KEY
# CLOUDINARY_CLOUD_NAME
# CLOUDINARY_API_KEY
# CLOUDINARY_API_SECRET
# JWT_SECRET
# EMAIL_USER
# EMAIL_APP_PASSWORD 