[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 3
healthcheckInterval = 10
restartPolicy = "on-failure"
numReplicas = 1

[variables]
NODE_ENV = "production"

# Add these as environment variables in Railway dashboard:
# DATABASE_URL (will be automatically added when you attach MySQL)
# FRONTEND_URL
# PAYSTACK_SECRET_KEY
# CLOUDINARY_CLOUD_NAME
# CLOUDINARY_API_KEY
# CLOUDINARY_API_SECRET
# JWT_SECRET
# EMAIL_USER
# EMAIL_APP_PASSWORD 