[build]
builder = "NIXPACKS"
buildCommand = "cd sneaky_backend && npm install"

[deploy]
startCommand = "cd sneaky_backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 15
healthcheckInterval = 10
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[service]
autoDeploy = false 